- type: entity
  parent: SquadBase
  id: SquadLancer
  name: Lancer Platoon
  components:
  - type: SquadTeam
    color: "#6CAD58"
    blacklistedSquadArmor:
    - Helmet
    - Armor
    - Gloves
    radio: MarineLancer
    accessLevels:
    - CMAccessAlpha
    minimapBackground:
     sprite: /Textures/_HALO14/Interface/map_blips.rsi
     state: background_lancer
